# Generated by Django 5.1.1 on 2024-12-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
    ]
