# Generated by Django 5.1.4 on 2024-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='time_length',
        ),
    ]
