# Generated by Django 5.1.1 on 2025-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_remove_song_time_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_file',
            new_name='audio',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_image',
            field=models.ImageField(default='', upload_to='song_images'),
        ),
    ]
