# Generated by Django 5.1.1 on 2025-01-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_rename_song_file_song_audio_alter_song_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='content_type',
        ),
    ]
